### ISSUE TITLE
Check of Sprint 1 outputs

### ISSUE THREAD

**Issue by 55Brian55** [jj1976/SSW555AgileMethodsCJBS#40]
Chris,
Checking outputs for Sprint 1 against user stories. All looks good except US 23, for duplicate name in GEDCOM file. Can you check if a duplicate name entry exists in the test file?

Thanks

**Comment by CCorrado** [comment]
@55brian55 US 23 -- did you work on that? I worked on US 25.... unique first names in families. I checked if, for children in a family, an individual with the same name and birth date exists in the children's dictionary. You can steal that logic for US 23 ;)

**Comment by 55Brian55** [comment]
Yeah,

I committed the code below for this - looks like it got squashed. . What would be easier 1) revise code below for current error format or add enhance to method with same name in Main? 

def unique_name_b_date(ind_dict):
    """
    Determines if individuals have unique names and birth dates"
    :param: ind_dict -- Individual dictionary containing all unique individuals
    :return: a list of ids for the individual dictionary which have identical names and identical birthdays or both.
    """
    name_list=[]
    birth_list=[]
    same_name_id=[]
    same_b_date_id=[]
    for indi_id, individual in (ind_dict.items()):
            name_list.append(individual.name)

            birth_list.append(individual.birthday)
    y=collections.Counter(name_list)
    print( 'the collection of individuals is', y)
    x=[i for i in y if y[i]>1]
    print( 'the duplicate names are ', x)
    
    v=collections.Counter(birth_list)
    print ('the collection of birthdays is', v)
    w=[i for i in v if v[i]>1]
    print( 'the duplicate births are ', w)
    
    for indi_id, individual in (ind_dict.items()):
        if  individual.name in x:    
            same_name_id.append(indi_id)
        if individual.birthday in w:
            same_b_date_id.append(indi_id)
    print( ' the ids who have duplicate names are',same_name_id)
    print( ' the ids who have duplicate birthdays are',same_b_date_id)
    
    print(name_list, birth_list)
    return same_name_id, same_b_date_id

**Comment by 55Brian55** [comment]
Chris,

Do you have time tonight to review this?

**Comment by CCorrado** [comment]
@55Brian55 i dont think that code will work. 

Your code will find everybody with the same name, and add it to a list. Then it will find everyone with the same birthday and add it to the list. Then it will print out all the people with the same birthdays and the same names. That's not the requirement in the excel doc. The requirement states: 
```
No more than one individual with the same name and birth date should appear in a GEDCOM file
```

You will need to create a `dictionary` of all users keyed by their `name` or `birthday`, with the value being either of the latter. Then, for each individual in the parent dictionary, check to see if for a person's name their birthday AND name matches an element in a separate dictionary with the same values. 

I think I cleaned this one up. But, its not being called anywhere in the parser. So all we need to do is call this during validation and we should be good to go :)

```
def unique_name_b_date(ind_dict):
    """
    Determines if individuals have unique names and birth dates
    :param: ind_dict -- Individual dictionary containing all unique individuals
    :return: True if individuals names and birth dates are unique or False otherwise and return error string.
    """
    indi_name_bday_dict = {}
    duplicates = []
    for indi_id in ind_dict:
        if indi_id in ind_dict:
            indi = ind_dict[indi_id]
            if indi.name in indi_name_bday_dict and indi_name_bday_dict[indi.name] == indi.birthday:
                duplicates.append(indi)
                print("ERROR: INDIVIDUAL: US23: {}: Individual with name: {} and birthday {} already exists".format(
                    indi.id, indi.name, indi.birthday))
            indi_name_bday_dict[indi.name] = indi.birthday
    # return whether or not any duplicates existed in the data set.
    return duplicates == []
```

**Comment by 55Brian55** [comment]
I probably overthought that one :)

I will update the test files when I get home from work.
Thanks

**Comment by CCorrado** [comment]
@55Brian55  I got it! no worries, i missed it during my refactor. It was a simple change, check #41 for the changes.
