### ISSUE TITLE
IPython execution

### ISSUE THREAD

**Issue by 55Brian55** [jj1976/SSW555AgileMethodsCJBS#44]
Chris,
I been reading about the IPython shell as a better tool to debug runtime issues with the program.

Do you know how I can run the GEDCOM Parser in IPython?

If I'm in the current working directory, is it simply:
%run GedcomParser.parse_gedcom_file(ged_file)?

- Thanks

**Comment by CCorrado** [comment]
Get PyCharm Community Edition :) it's free. And debugger is built in.


Chris

**Comment by 55Brian55** [comment]
Thanks Chris - I'll check out PyCharm.
