### ISSUE TITLE
US21 - Correct gender for role

### ISSUE THREAD

**Issue by CCorrado** [jj1976/SSW555AgileMethodsCJBS#5]
Husband in family should be male and wife in family should be female

**Comment by CCorrado** [comment]
@55Brian55 for the report...
Est. Size = 20 LOC
Est. Time = 2 hours
Act. Size = 11 lines (without tests)... 67 (with tests)
Act. Time = 3 hours

**Comment by CCorrado** [comment]
See #23 for code.... wondering if I'm not linking PRs to Issues correctly...

**Comment by 55Brian55** [comment]
Thanks, I'll update the report.

**Comment by CCorrado** [comment]
Awesome. Closing this issue then.
