### ISSUE TITLE
Sprint Report Update

### ISSUE THREAD

**Issue by 55Brian55** [jj1976/SSW555AgileMethodsCJBS#50]
[TeamSSW55AgileMethodsCJBS_Report team update Mar 04.xlsx](https://github.com/jj1976/SSW555AgileMethodsCJBS/files/1778576/TeamSSW55AgileMethodsCJBS_Report.team.update.Mar.04.xlsx)

Morning Team,

Please update the attached Sprint 2 Team Report by closing out your US with actuals where completed, Also please identify your user stories for Sprint 3. We'll discuss shortly.
-Thanks

**Comment by CCorrado** [comment]
If we all update the file there's going to be a bunch of conflicts....

My Sprint 2 Metrics: 

U.S. 38
Estimated LOC: 20
Estimated Time: 120
Actual LOC: 23
Actual Time: 70

U.S. 39 
Estimated LOC: 20
Estimated Time: 120
Actual LOC: 28
Actual Time: 60

For sprint 3 I'll take U.S. 27 and U.S. 42.

**Comment by 55Brian55** [comment]
I have updated the Sprint Report for the Team based on your feedback. Thanks
