### ISSUE TITLE
sprint 2 update

### ISSUE THREAD

**Issue by jj1976** [jj1976/SSW555AgileMethodsCJBS#53]
#_30_
est size 20
est time 150

actual size 15
actual time 150

#_31_
est size 15
est time 120

actual size 20
actual time 120

**Comment by 55Brian55** [comment]
Please add new estimates for sprint 3

**Comment by rsukitha** [comment]
US17 | No marriages to descendants 
est size 30 
est time 180 

actual size 4
actual time 80

US04 | Marriage before divorce 
est size 30
est time 180 
actual size 12 
actual time 60

**Comment by jj1976** [comment]
Sprint #3
#_11_
est size 15
est time 120

#_12_
est size 15
est time 120

**Comment by rsukitha** [comment]
Sprint 3

US05 | Marriage before death 
estimate size 20 
estimate time 60

US06 | Divorce before death 

estimate size 20 
estimate time 60

**Comment by 55Brian55** [comment]
Sukitah, Thanks.

Please send me your estimates for US05 and US06 LOC, Story Points and time.


-        Brian

**Comment by 55Brian55** [comment]
I believe this issue can now be closed. Brian

**Comment by CCorrado** [comment]
closing per @55Brian55
