### ISSUE TITLE
US22 - Unique IDs

### ISSUE THREAD

**Issue by CCorrado** [jj1976/SSW555AgileMethodsCJBS#6]
All individual IDs should be unique and all family IDs should be unique.

**Comment by 55Brian55** [comment]
Team,

I want to modify the parse_valid_results method to use the get method on the dictionary per below.  Please comment on this approach. - Thanks

def parse_valid_results(results):
    """
    Method to parse valid results from the GEDCOM file and return INDI/FAM dicts indexed by ID

    :param results -- List of valid GEDCOM results data formatted 'level, tag, valid, args'
    """
    families = {}
    individuals = {}
    current_fam_id = ""
    current_indi_id = ""
    results_iter = iter(results)
    for result in results_iter:
        if result[1] == 'FAM':
            families[result[3]] = Family(result[3])
            
            print ' the family  id is ',result[3]
            
            if (families.get(result[3],'None'))=='None':
                current_fam_id = result[3]
            else: print 'duplicate family id %s ' %result[3]
