### ISSUE TITLE
US 18 - Siblings should not marry

### ISSUE THREAD

**Issue by CCorrado** [jj1976/SSW555AgileMethodsCJBS#73]
Siblings should not marry one another

Estimate LOC: 10
Estimate Time: 120

**Comment by CCorrado** [comment]
Estimate LOC: 10
Estimate Time: 120
Actual LOC: 21
Actual Time: 120

**Comment by CCorrado** [comment]
@55Brian55  US 18 details are here

**Comment by 55Brian55** [comment]
Got it. Thanks
